# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='corrreo',
            new_name='correo',
        ),
    ]
