# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20171105_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
